---
  - hosts: dev
    become: yes
    tasks:
      - name: Install packages
        action: yum name=httpd state=present
      - name: Start Apache server 
        action: service name=httpd state=started enabled=True
      - name: Deploy static website
        action: copy src=index.html dest=/var/www/html/
