---#Playbook to install apache server on dev using linux
 - hosts: dev
   become: yes
   tasks:
       - name: Install apche on dev
         action: yum name=httpd state=present
       - name: Copy index.html to dev server
         action: copy src='index.html' dest='/var/www/html/'
       - name: Start httpd
         action: service name=httpd state=started        
